# Generated by Django 4.2.13 on 2026-06-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IntegratedApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                ("slug", models.SlugField(unique=True, verbose_name="شناسه")),
                (
                    "app_type",
                    models.CharField(
                        choices=[
                            ("bi", "هوش تجاری"),
                            ("bpm", "مدیریت فرآیند"),
                            ("attendance", "حضور و غیاب"),
                            ("hr", "منابع انسانی"),
                            ("other", "سایر"),
                        ],
                        max_length=20,
                        verbose_name="نوع",
                    ),
                ),
                ("url", models.URLField(verbose_name="آدرس")),
                (
                    "icon_class",
                    models.CharField(
                        default="bi-app", max_length=50, verbose_name="کلاس آیکون"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "open_in_new_tab",
                    models.BooleanField(
                        default=True, verbose_name="باز کردن در تب جدید"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "اپلیکیشن",
                "verbose_name_plural": "اپلیکیشن\u200cها",
                "db_table": "dashboard_app",
                "ordering": ["order", "name"],
            },
        ),
    ]
