# Generated by Django 4.2.13 on 2026-06-15 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام شرکت")),
                (
                    "short_name",
                    models.CharField(max_length=50, verbose_name="نام کوتاه"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="company_logos/",
                        verbose_name="لوگو",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "شرکت",
                "verbose_name_plural": "شرکت\u200cها",
                "db_table": "org_company",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام دپارتمان")),
                (
                    "code",
                    models.CharField(blank=True, max_length=20, verbose_name="کد"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="organization.company",
                        verbose_name="شرکت",
                    ),
                ),
            ],
            options={
                "verbose_name": "دپارتمان",
                "verbose_name_plural": "دپارتمان\u200cها",
                "db_table": "org_department",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان پست")),
                (
                    "code",
                    models.CharField(blank=True, max_length=20, verbose_name="کد"),
                ),
                ("level", models.IntegerField(default=1, verbose_name="سطح")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="organization.department",
                        verbose_name="دپارتمان",
                    ),
                ),
            ],
            options={
                "verbose_name": "پست سازمانی",
                "verbose_name_plural": "پست\u200cهای سازمانی",
                "db_table": "org_position",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "personnel_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="شماره پرسنلی"
                    ),
                ),
                ("national_id", models.CharField(max_length=10, verbose_name="کد ملی")),
                ("hire_date", models.DateField(verbose_name="تاریخ استخدام")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="تلفن"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="organization.company",
                        verbose_name="شرکت",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="organization.department",
                        verbose_name="دپارتمان",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="organization.position",
                        verbose_name="پست سازمانی",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "کارمند",
                "verbose_name_plural": "کارمندان",
                "db_table": "org_employee",
            },
        ),
        migrations.AddField(
            model_name="department",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_departments",
                to="organization.employee",
                verbose_name="مدیر",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="organization.department",
                verbose_name="دپارتمان والد",
            ),
        ),
    ]
