# Generated by Django 4.2.13 on 2026-06-15 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        ("dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام نقش")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="dashboard.integratedapp",
                        verbose_name="اپلیکیشن",
                    ),
                ),
            ],
            options={
                "verbose_name": "نقش",
                "verbose_name_plural": "نقش\u200cها",
                "db_table": "perm_app_role",
            },
        ),
        migrations.CreateModel(
            name="EmployeeAppPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ اعطا"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_permissions",
                        to="dashboard.integratedapp",
                        verbose_name="اپلیکیشن",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_permissions",
                        to="organization.employee",
                        verbose_name="کارمند",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعطا شده توسط",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.approle",
                        verbose_name="نقش",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسترسی کارمند",
                "verbose_name_plural": "دسترسی\u200cهای کارمندان",
                "db_table": "perm_employee_app",
                "unique_together": {("employee", "app", "role")},
            },
        ),
        migrations.CreateModel(
            name="DepartmentAppPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_permissions",
                        to="dashboard.integratedapp",
                        verbose_name="اپلیکیشن",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_permissions",
                        to="organization.department",
                        verbose_name="دپارتمان",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.approle",
                        verbose_name="نقش",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسترسی دپارتمان",
                "verbose_name_plural": "دسترسی\u200cهای دپارتمان\u200cها",
                "db_table": "perm_department_app",
                "unique_together": {("department", "app", "role")},
            },
        ),
    ]
