# Generated by Django 4.2.13 on 2026-06-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ADConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False, verbose_name="فعال")),
                (
                    "server_uri",
                    models.CharField(
                        default="ldap://localhost",
                        max_length=200,
                        verbose_name="آدرس سرور",
                    ),
                ),
                (
                    "bind_dn",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Bind DN"
                    ),
                ),
                (
                    "bind_password",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="رمز Bind"
                    ),
                ),
                (
                    "user_search_base",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="پایه جستجوی کاربران"
                    ),
                ),
                (
                    "user_search_filter",
                    models.CharField(
                        default="(sAMAccountName=%(user)s)",
                        max_length=200,
                        verbose_name="فیلتر جستجو",
                    ),
                ),
                (
                    "group_search_base",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="پایه جستجوی گروه\u200cها",
                    ),
                ),
                (
                    "require_group",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="گروه اجباری"
                    ),
                ),
                (
                    "use_tls",
                    models.BooleanField(default=False, verbose_name="استفاده از TLS"),
                ),
                (
                    "timeout",
                    models.IntegerField(
                        default=5, verbose_name="تایم\u200cاوت (ثانیه)"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "تنظیمات AD",
                "db_table": "settings_ad_config",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="پورتال سازمانی",
                        max_length=100,
                        verbose_name="نام سایت",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="site/", verbose_name="لوگو"
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#0d6efd", max_length=7, verbose_name="رنگ اصلی"
                    ),
                ),
                (
                    "allow_local_login",
                    models.BooleanField(default=True, verbose_name="اجازه ورود محلی"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "تنظیمات سایت",
                "db_table": "settings_site",
            },
        ),
    ]
